apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grad.serviceAccount.name }}
  labels:
    {{- include "grad.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grad.fullname" . }}-runner-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "grad.fullname" . }}-runner-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "grad.fullname" . }}-runner-manager
subjects:
- kind: ServiceAccount
  name: {{ .Values.grad.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}