# Example configuration file for gractl
# Copy this file to .gractl.toml in your working directory and modify as needed

[server]
# gRPC server address for grad service
# Default: localhost:9090
address = "localhost:9090"

[s3]
# S3 bucket name for workspace data
# This will be used as default when creating runners with S3 workspace
bucket = "gra-dataset"

# S3 endpoint URL (optional)
# Leave empty for AWS S3, or specify custom endpoint for S3-compatible services
endpoint = ""

# S3 path prefix within the bucket (optional)
# Useful for organizing data within a bucket
prefix = ""

# AWS region (optional)
# Default: us-east-1
region = "us-east-1"

# AWS credentials
# These will be automatically injected as environment variables for runners
# You can also set these via environment variables:
#   GRACTL_S3_ACCESS_KEY_ID
#   GRACTL_S3_SECRET_ACCESS_KEY
#   GRACTL_S3_SESSION_TOKEN
access_key_id = "your-access-key-id"
secret_access_key = "your-secret-access-key"
session_token = "your-session-token"  # Optional, for temporary credentials

# Mount S3 bucket as read-only
# Default: false
read_only = false

# Environment variables can override config file values:
# GRACTL_SERVER_ADDRESS=localhost:9090
# GRACTL_S3_BUCKET=my-bucket
# GRACTL_S3_ENDPOINT=https://s3.example.com
# GRACTL_S3_PREFIX=my-prefix
# GRACTL_S3_REGION=us-west-2
# GRACTL_S3_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
# GRACTL_S3_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# GRACTL_S3_SESSION_TOKEN=token
# GRACTL_S3_READ_ONLY=true
