apiVersion: v1
kind: Service
metadata:
  name: grad-service
  labels:
    app: grad
    component: grad-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30080
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
    nodePort: 30090
  selector:
    app: grad
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grad-service-account
  labels:
    app: grad
    component: grad-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grad-runner-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grad-runner-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grad-runner-manager
subjects:
- kind: ServiceAccount
  name: grad-service-account
  namespace: default